image: 'registry.gitlab.com/oneira/nikola-builder-image/nikola-builder:latest'

before_script:
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

build-and-deploy:
  script:
    - nikola build
    - nikola deploy
    - if [[ ! -z "${ANNOUNCE_HOOK}" ]]; then nikola announce -u  $ANNOUNCE_HOOK; fi
    - if [[ ! -z "${MASTODON_TOKEN}" ]]; then nikola announce-mastodon -t  "$MASTODON_TOKEN" -n "https://floss.social"; fi