image: 'python:3.7-buster'

before_script:
  - pip install --upgrade "Nikola[extras]" discord-webhook
  - apt-get update
  - apt-get install --assume-yes rsync openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir ~/.ssh
  - chmod 600 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build-and-deploy:
  script:
    - nikola build
    - rsync -av --delete -e "ssh -p 7658 " output/ lyly@mad-scientists.net:/srv/KriekData1/net.mad-scientists/la-minute-culturelle
    - if [[ ! -z "${ANNOUNCE_HOOK}" ]]; then nikola announce -u  $ANNOUNCE_HOOK; fi