image: 'python:3.7-buster'

before_script:
  - pip install --upgrade "Nikola[extras]" discord-webhook Mastodon.py
  - apt-get update
  - apt-get install --assume-yes rsync openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir ~/.ssh
  - chmod 600 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build-and-deploy:
  script:
    - nikola build
    - nikola deploy
    - if [[ ! -z "${ANNOUNCE_HOOK}" ]]; then nikola announce -u  $ANNOUNCE_HOOK; fi
    - if [[ ! -z "${MASTODON_TOKEN}" ]]; then nikola announce-mastodon -t  "$MASTODON_TOKEN" -n "https://floss.social"; fi