image: 'python:3.7-buster'

before_script:
  - ping -c2 mad-scientists.net
  - pip install --upgrade "Nikola[extras]"
  - apt-get update
  - apt-get install --assume-yes rsync openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -


build-and-deploy:
  script:
    - nikola build
    - rsync -av --delete output/ lyly@mad-scientists.net:/srv/KriekData1/net.mad-scientists/la-minute-culturelle