image: 'python:3.7-buster'

before_script:
  - ping -c2 mad-scientists.net
  - host mad-scientists.net
  - pip install --upgrade "Nikola[extras]"
  - apt-get update
  - apt-get install --assume-yes rsync

build-and-deploy:
  script:
    - nikola build
    - nikola deploy
